"""Local complementation and LC-orbit enumeration (spec §8.2).

tau_a(G) toggles every edge WITHIN the neighborhood N(a) (Bouchet); LC-equivalence
is generated by these. lc_orbit does a BFS applying tau_v at every vertex, deduping
by the GraphState value, up to an orbit-size cap (orbits blow up past n=9, so the
cap is a declared bound, not a silent truncation -- it raises if hit).
"""

from __future__ import annotations

from collections import deque

from empiricist.domain.p5.graphstate import GraphState

DEFAULT_ORBIT_CAP = 200_000


class OrbitTooLarge(Exception):
    """The LC orbit exceeded the cap before closing (declare a larger cap or n0)."""


def local_complement(gs: GraphState, a: int) -> GraphState:
    """tau_a(gs): toggle every edge within N(a) (the clique-complement on N(a)).

    a's own edges (to its neighbors) are unchanged; only pairs b, c in N(a) can
    flip. This is an involution: local_complement(local_complement(gs, a), a) == gs.
    """
    nbrs = sorted(gs.neighbors(a))
    edges = set(gs.edges)
    for i in range(len(nbrs)):
        for j in range(i + 1, len(nbrs)):
            b, c = nbrs[i], nbrs[j]
            e = (b, c) if b < c else (c, b)
            if e in edges:
                edges.discard(e)
            else:
                edges.add(e)
    return GraphState(n=gs.n, edges=edges)


def lc_orbit(gs: GraphState, *, cap: int = DEFAULT_ORBIT_CAP) -> list[GraphState]:
    """The full LC orbit of gs (BFS under tau_v for all v), deduped by GraphState value.

    Raises OrbitTooLarge if the orbit exceeds `cap` before closing.
    """
    seen: set[GraphState] = {gs}
    queue: deque[GraphState] = deque([gs])
    while queue:
        g = queue.popleft()
        for v in range(g.n):
            h = local_complement(g, v)
            if h not in seen:
                if len(seen) >= cap:
                    raise OrbitTooLarge(f"LC orbit exceeded cap={cap}")
                seen.add(h)
                queue.append(h)
    return sorted(seen, key=lambda g: (len(g.edges), sorted(g.edges)))
