"""Local complementation and LC-orbit enumeration (spec §8.2).

tau_a(G) toggles every edge WITHIN the neighborhood N(a) (Bouchet); LC-equivalence
is generated by these. lc_orbit does a BFS applying tau_v at every vertex, deduping
by the GraphState value, up to an orbit-size cap (orbits blow up past n=9, so the
cap is a declared bound, not a silent truncation -- it raises if hit).
"""

from __future__ import annotations

from collections import deque

import numpy as np

from empiricist.domain.p5.graphstate import GraphState

DEFAULT_ORBIT_CAP = 200_000


class OrbitTooLarge(Exception):
    """The LC orbit exceeded the cap before closing (declare a larger cap or n0)."""


def local_complement(gs: GraphState, a: int) -> GraphState:
    """tau_a(gs): toggle every edge within N(a) (the clique-complement on N(a)).

    a's own edges (to its neighbors) are unchanged; only pairs b, c in N(a) can
    flip. This is an involution: local_complement(local_complement(gs, a), a) == gs.
    """
    nbrs = sorted(gs.neighbors(a))
    edges = set(gs.edges)
    for i in range(len(nbrs)):
        for j in range(i + 1, len(nbrs)):
            b, c = nbrs[i], nbrs[j]
            e = (b, c) if b < c else (c, b)
            if e in edges:
                edges.discard(e)
            else:
                edges.add(e)
    return GraphState(n=gs.n, edges=edges)


def lc_orbit(gs: GraphState, *, cap: int = DEFAULT_ORBIT_CAP) -> list[GraphState]:
    """The full LC orbit of gs (BFS under tau_v for all v), deduped by GraphState value.

    Raises OrbitTooLarge if the orbit exceeds `cap` before closing.
    """
    seen: set[GraphState] = {gs}
    queue: deque[GraphState] = deque([gs])
    while queue:
        g = queue.popleft()
        for v in range(g.n):
            h = local_complement(g, v)
            if h not in seen:
                if len(seen) >= cap:
                    raise OrbitTooLarge(f"LC orbit exceeded cap={cap}")
                seen.add(h)
                queue.append(h)
    return sorted(seen, key=lambda g: (len(g.edges), sorted(g.edges)))


def _gf2_rank(M: np.ndarray) -> int:
    """Rank of M over GF(2) via Gaussian elimination (row echelon, mod 2)."""
    M = M.copy() % 2
    rows, cols = M.shape
    r = 0
    for c in range(cols):
        piv = next((i for i in range(r, rows) if M[i, c]), None)
        if piv is None:
            continue
        M[[r, piv]] = M[[piv, r]]
        for i in range(rows):
            if i != r and M[i, c]:
                M[i] = (M[i] + M[r]) % 2
        r += 1
    return r


def cut_rank_profile(gs: GraphState) -> tuple[int, ...]:
    """LC-invariant: sorted multiset of GF(2) cut-ranks over all bipartitions.

    For a bipartition (X, V\\X), the cut-rank is the GF(2) rank of the off-diagonal
    block A[X, V\\X]. The sorted multiset over all non-trivial bipartitions is
    invariant under local complementation (rank-width theory): this is a one-sided
    pre-filter -- a profile mismatch certifies NON-equivalence, but equality does
    not certify equivalence.
    """
    A = gs.adjacency().astype(np.int64)
    n = gs.n
    ranks = []
    for mask in range(1, (1 << n) - 1):  # non-trivial bipartitions
        X = [i for i in range(n) if mask & (1 << i)]
        Y = [i for i in range(n) if not (mask & (1 << i))]
        ranks.append(_gf2_rank(A[np.ix_(X, Y)]))
    return tuple(sorted(ranks))
