/-
  EmpiricistLean.LocalComp

  Local complementation on simple graphs (the `τ_v` operation of the
  P5 graph-state model) and LC-equivalence: the equivalence relation
  generated by single local complementations and graph isomorphisms
  (relabellings).

  Target declaration: `Empiricist.lcEquiv_equivalence`.
-/
import Mathlib.Combinatorics.SimpleGraph.Basic
import Mathlib.Combinatorics.SimpleGraph.Maps
import Mathlib.Logic.Relation
import EmpiricistLean.Basic

namespace Empiricist

variable {V : Type*}

/-- Local complementation `τ_v` at a vertex `v`: toggle every edge lying
within the neighbourhood of `v`.  The `x`–`y` edge is flipped iff `x ≠ y`
and *both* `x` and `y` are adjacent to `v`; in particular `v`'s own edges
and all pairs not inside `N(v)` are unchanged. -/
def localComplement (G : SimpleGraph V) (v : V) : SimpleGraph V where
  Adj x y := Xor' (G.Adj x y) (x ≠ y ∧ G.Adj x v ∧ G.Adj y v)
  symm := by
    constructor
    intro x y h
    unfold Xor' at h ⊢
    rcases h with ⟨ha, hb⟩ | ⟨⟨hne, hxv, hyv⟩, hb⟩
    · exact Or.inl ⟨ha.symm, fun hc => hb ⟨hc.1.symm, hc.2.2, hc.2.1⟩⟩
    · exact Or.inr ⟨⟨hne.symm, hyv, hxv⟩, fun hc => hb hc.symm⟩
  loopless := by
    constructor
    intro x h
    unfold Xor' at h
    rcases h with ⟨ha, -⟩ | ⟨⟨hne, -⟩, -⟩
    · exact G.irrefl ha
    · exact hne rfl

/-- Adjacency rule of local complementation, by definitional unfolding. -/
theorem localComplement_adj (G : SimpleGraph V) (v x y : V) :
    (localComplement G v).Adj x y ↔
      Xor' (G.Adj x y) (x ≠ y ∧ G.Adj x v ∧ G.Adj y v) :=
  Iff.rfl

/-- The edges at `v` itself are unchanged by `τ_v` (since `v ∉ N(v)`). -/
theorem localComplement_adj_self (G : SimpleGraph V) (v x : V) :
    (localComplement G v).Adj x v ↔ G.Adj x v := by
  show Xor' (G.Adj x v) (x ≠ v ∧ G.Adj x v ∧ G.Adj v v) ↔ G.Adj x v
  unfold Xor'
  constructor
  · rintro (⟨h, -⟩ | ⟨⟨-, -, hvv⟩, -⟩)
    · exact h
    · exact absurd hvv G.irrefl
  · intro h
    exact Or.inl ⟨h, fun hc => G.irrefl hc.2.2⟩

/-- Propositional xor cancels itself: `(a ⊕ b) ⊕ b ↔ a`. -/
theorem xor_xor_cancel (a b : Prop) : Xor' (Xor' a b) b ↔ a := by
  unfold Xor'
  constructor
  · rintro (⟨hab | hab, hnb⟩ | ⟨hb, hn⟩)
    · exact hab.1
    · exact absurd hab.1 hnb
    · exact Classical.byContradiction fun hna => hn (Or.inr ⟨hb, hna⟩)
  · intro ha
    exact (Classical.em b).elim
      (fun hb => Or.inr ⟨hb, fun h => h.elim (fun h' => h'.2 hb) (fun h' => h'.2 ha)⟩)
      (fun hnb => Or.inl ⟨Or.inl ⟨ha, hnb⟩, hnb⟩)

/-- Local complementation is an involution: `τ_v (τ_v G) = G`. -/
theorem localComplement_involutive (G : SimpleGraph V) (v : V) :
    localComplement (localComplement G v) v = G := by
  ext x y
  rw [localComplement_adj, localComplement_adj_self, localComplement_adj_self,
    localComplement_adj]
  exact xor_xor_cancel _ _

/-- One step of LC-equivalence: a single local complementation, or a single
graph isomorphism (relabelling of vertices). -/
def LCStep (H₁ H₂ : SimpleGraph V) : Prop :=
  (∃ v, localComplement H₁ v = H₂) ∨ Nonempty (H₁ ≃g H₂)

/-- A single LC step is symmetric.  The local-complementation case uses the
involution `localComplement_involutive`; the isomorphism case maps
`SimpleGraph.Iso.symm` through the `Nonempty` witness. -/
theorem lcStep_symm {H₁ H₂ : SimpleGraph V} (h : LCStep H₁ H₂) : LCStep H₂ H₁ := by
  unfold LCStep at h ⊢
  rcases h with ⟨v, hv⟩ | he
  · exact Or.inl ⟨v, by rw [← hv, localComplement_involutive]⟩
  · exact Or.inr (he.map SimpleGraph.Iso.symm)

/-- LC-equivalence: the equivalence relation generated by single LC steps. -/
def LCEquiv : SimpleGraph V → SimpleGraph V → Prop :=
  Relation.EqvGen LCStep

/-- A single local complementation is an LC-equivalence. -/
theorem lcEquiv_localComplement (G : SimpleGraph V) (v : V) :
    LCEquiv G (localComplement G v) :=
  Relation.EqvGen.rel G (localComplement G v) (Or.inl ⟨v, rfl⟩)

/-- Symmetry of LC-equivalence, proved by pushing symmetry down to single
steps via `lcStep_symm` (and hence via `localComplement_involutive`). -/
theorem lcEquiv_symm {H₁ H₂ : SimpleGraph V} (h : LCEquiv H₁ H₂) :
    LCEquiv H₂ H₁ := by
  have h' : Relation.EqvGen LCStep H₁ H₂ := h
  clear h
  induction h' with
  | rel x y hxy => exact Relation.EqvGen.rel y x (lcStep_symm hxy)
  | refl x => exact Relation.EqvGen.refl x
  | symm x y hxy _ => exact hxy
  | trans x y z _ _ ih₁ ih₂ => exact Relation.EqvGen.trans z y x ih₂ ih₁

/-- **Target.**  LC-equivalence is a genuine equivalence relation on simple
graphs.  Reflexivity and transitivity come from the generated closure;
symmetry is routed through `lcEquiv_symm` → `lcStep_symm` →
`localComplement_involutive`, so this declaration transitively depends on
the involutivity of local complementation. -/
theorem lcEquiv_equivalence : Equivalence (@LCEquiv V) where
  refl G := Relation.EqvGen.refl G
  symm h := lcEquiv_symm h
  trans h₁ h₂ := Relation.EqvGen.trans _ _ _ h₁ h₂

end Empiricist